TaskManager_taskback/ViewModels/TaskDataViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TaskManager_taskback.Models;
using TaskManager_taskback.Utilities;

namespace TaskManager_taskback.ViewModels
{
    public class TaskDataViewModel
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public DateTime CreatedOn { get; set; }
        public TaskType TaskType { get; set; }
        public TaskProgressStatus TaskStatus { get; set; }
        public IEnumerable<CommentsDataModel> Comments { get; set; }
    }
}

TaskManager_taskback/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TaskManager_taskback.Extensions;
using TaskManager_taskback.Models;
using TaskManager_taskback.Services;

namespace TaskManager_taskback.Controllers
{
    public class CommentsController : Controller
    {
        private IUserService _userService;
        private ITaskService _taskService;
        public CommentsController(
                IUserService userService,
                ITaskService taskService
            )
        {
            _userService = userService;
            _taskService = taskService;
        }
        public ActionResult Index()
        {
            return View();
        }
        // GET: Comments/Details/5
        public async Task<IActionResult> Details(int id)
        {
            return View();
        }

        // GET: Comments/Create
        public async Task<IActionResult> Create()
        {
            return View();
        }

        // POST: Comments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CommentsDataModel comment, int taskId)
        {
            try
            {
                var userId = User.GetUserId();
                var userObj = await _userService.GetUserData(userId);
                comment.User = userObj;
                await _taskService.AddCommentToTask(comment, taskId);
                return RedirectToAction("Details", "TaskData", new { Id =  taskId});
            }
            catch
            {
                throw;//return RedirectToAction("Details", "TaskData", new { Id = taskId });
            }
        }

        // GET: Comments/Edit/5
        public async Task<IActionResult> Edit(int taskId, int id)
        {
            var comment = await _taskService.GetCommentById(taskId, id);
            return View(comment);
        }

        // POST: Comments/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int taskId, CommentsDataModel model)
        {
            try
            {
                await _taskService.UpdateComment(taskId, model);
                return RedirectToAction("Details", "TaskData", new { Id = taskId });
            }
            catch
            {
                throw;
            }
        }

        // GET: Comments/Delete/5
        
        public async Task<IActionResult> Delete(int taskId, int id)
        {
            var comment = await _taskService.GetCommentById(taskId, id);
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, int taskId, string f = null)
        {
            try
            {
                var comment = await _taskService.GetCommentById(taskId, id);
                await _taskService.DeleteCommentFromTask(comment, taskId);
                return RedirectToAction("Details", "TaskData", new { Id = taskId });
            }
            catch
            {
                return View();
            }
        }
    }
}

TaskManager_taskback/Controllers/TaskDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TaskManager_taskback.Extensions;
using TaskManager_taskback.Models;
using TaskManager_taskback.Services;
using TaskManager_taskback.Utilities;
using TaskManager_taskback.ViewModels;

namespace TaskManager_taskback.Controllers
{
    public class TaskDataController : Controller
    {
        private ITaskService _taskService;
        private IMapper _mapper;
        public TaskDataController(
                ITaskService taskService,
                IMapper mapper
            )
        {
            _taskService = taskService;
            _mapper = mapper;
        }
        // GET: TaskData
        public async Task<IActionResult> Index()
        {
            var taskModels = await _taskService.GetAllTasks();

            var taskViewModels = _mapper.Map<IEnumerable<TaskDataViewModel>>(taskModels);
            return View(taskViewModels);
        }

        // GET: TaskData/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var task = await _taskService.GetTaskWithComments(id);
            var taskViewModel = _mapper.Map<TaskDataViewModel>(task);
            return View(taskViewModel);
        }

        // GET: TaskData/Create
        public async Task<IActionResult> Create()
        {
            return View();
        }

        // POST: TaskData/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TaskDataViewModel model)
        {
            try
            {
                // TODO: Add insert logic here      
                if (ModelState.IsValid)
                {
                    var taskModel = _mapper.Map<TaskDataModel>(model);
                    await _taskService.AddNewTask(taskModel);
                    return RedirectToAction(nameof(Index));
                }
                    
                throw new MissingFieldException();                
            }
            catch
            {
                return View();
            }
        }

        // GET: TaskData/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var task = await _taskService.GetTask(id);
            var taskViewModel = _mapper.Map<TaskDataViewModel>(task);
            return View(taskViewModel);
        }

        // POST: TaskData/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TaskDataViewModel model)
        {
            try
            {
                var taskModel = _mapper.Map<TaskDataModel>(model);
                await _taskService.UpdateTask(taskModel);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TaskData/Delete/5
        public async Task<IActionResult> Delete(int id)
        {

            var task = await _taskService.GetTask(id);
            var taskViewModel = _mapper.Map<TaskDataViewModel>(task);
            return View(taskViewModel);
        }

        // POST: TaskData/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, TaskDataViewModel collection)
        {
            try
            {
                var taskModel = _mapper.Map<TaskDataModel>(collection);
                await _taskService.DeleteTask(taskModel);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

TaskManager_taskback/Views/TaskData/Create.cshtml
@model TaskManager_taskback.ViewModels.TaskDataViewModel

@{
    ViewData["Title"] = "Create Task";
}

<h2>Create Task</h2>

<h4>TaskDataViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DropDownList("TaskType",
                      new SelectList(Enum.GetValues(typeof(TaskManager_taskback.Utilities.TaskType))), "Select type", new { @class = "form-control" })
                <span asp-validation-for="TaskType" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DropDownList("TaskStatus",
                new SelectList(Enum.GetValues(typeof(TaskManager_taskback.Utilities.TaskProgressStatus))), "Select status", new { @class = "form-control" })
                <span asp-validation-for="TaskStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TaskManager_taskback/Views/TaskData/Delete.cshtml
@model TaskManager_taskback.ViewModels.TaskDataViewModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TaskDataViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TaskType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TaskType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TaskStatus)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TaskStatus)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TaskManager_taskback/Views/TaskData/Details.cshtml
@model TaskManager_taskback.ViewModels.TaskDataViewModel

@{
    ViewData["Title"] = "TaskDetails";
}

<h2>TaskDetails</h2>

<div>
    <h4>TaskDataViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TaskType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TaskType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TaskStatus)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TaskStatus)
        </dd>
    </dl>


    <div class="comments">
        <h3>Comments</h3>
        @{

            

                if (User.Identity.IsAuthenticated)
                {
                    <form asp-action="Create" asp-controller="Comments">
                        <textarea asp-for="Description" class="form-control"></textarea>
                        <input name="taskId" type="hidden" value="@Model.Id" />
                        <input type="submit" value="Comment" class="btn Btn-Primary" />
                    </form>
                }
                else
                {
                    <h3>Please sign in to comment</h3>
                }
            if (Model.Comments != null && Model.Comments.Any())
            {
                
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Description)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Comments)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </td>
                                    <td>
                                        <a asp-controller="Comments" asp-route-id="@item.Id" asp-action="Edit" asp-route-taskId="@Model.Id">Edit</a>
                                        <a asp-controller="Comments" asp-route-id="@item.Id" asp-action="Delete" asp-route-taskId="@Model.Id">Delete</a>
                                    </td>   
                                </tr>
                            }
                        </tbody>
                    </table>

                
            }

        }



    </div>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

TaskManager_taskback/Views/TaskData/Edit.cshtml
@model TaskManager_taskback.ViewModels.TaskDataViewModel
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>TaskDataViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <select asp-for="TaskType" class="form-control">
                    @{
                        foreach (var item in Enum.GetValues(typeof(TaskManager_taskback.Utilities.TaskType)))
                        {
                            if (item.Equals(Model.TaskType))
                            {
                                <option value="@item" selected>@item</option>
                            }
                            else
                            {
                                <option value="@item">@item</option>
                            }
                        }
                    }
                </select>
                <span asp-validation-for="TaskType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <select asp-for="TaskStatus" class=" form-control">
                    @{
                        foreach (var item in Enum.GetValues(typeof(TaskManager_taskback.Utilities.TaskProgressStatus)))
                        {
                            if (item.Equals(Model.TaskStatus))
                            {
                                <option value="@item" selected>@item</option>
                            }
                            else
                            {
                                <option value="@item">@item</option>
                            }
                        }
                    }
                </select>
                <span asp-validation-for="TaskStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TaskManager_taskback/Views/TaskData/Index.cshtml
@model IEnumerable<TaskManager_taskback.ViewModels.TaskDataViewModel>
@{
    ViewData["Title"] = "Index";
}

<h2>Tasks</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaskType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaskStatus)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaskType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaskStatus)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>